// lib/products.ts
export type Product = {
  id: number
  name: string
  slug: string
  category: string
  description: string
  price: string
  image: string
  features: string[]
}

export const products: Product[] = [
  {
    id: 1,
    name: "Botón de Pánico",
    slug: "boton-panico",
    category: "Seguridad Vehicular",
    description: "Dispositivo de alerta inmediata para situaciones de emergencia.",
    price: "A cotizar",
    image: "/img/equipos/boton-panico.png",
    features: ["Activación rápida", "Alerta en tiempo real", "Uso discreto"],
  },
  {
    id: 2,
    name: "Micrófono",
    slug: "microfono",
    category: "Comunicación",
    description: "Permite grabación o comunicación de audio dentro del vehículo.",
    price: "A cotizar",
    image: "/img/equipos/microfono.png",
    features: ["Alta sensibilidad", "Instalación sencilla", "Calidad de audio"],
  },
  {
    id: 3,
    name: "Contacto Magnético",
    slug: "contacto-magnetico",
    category: "Sensores de Seguridad",
    description: "Sensor de apertura/cierre ideal para puertas o compartimentos.",
    price: "A cotizar",
    image: "/img/equipos/contacto-magnetico.png",
    features: ["Alta durabilidad", "Instalación adaptable", "Resistente"],
  },
  {
    id: 4,
    name: "Buzzer o Sirena",
    slug: "sirena",
    category: "Alarmas",
    description: "Dispositivo de alerta sonora para disuasión y notificación.",
    price: "A cotizar",
    image: "/img/equipos/sirena.png",
    features: ["Alto volumen", "Bajo consumo", "Diseño compacto"],
  },
  {
    id: 5,
    name: "Kit de Comunicación Manos Libres",
    slug: "kit-manos-libres",
    category: "Comunicación",
    description: "Sistema de comunicación sin distracciones para choferes.",
    price: "A cotizar",
    image: "/img/equipos/kit-manos-libres.png",
    features: ["Audio nítido", "Instalación en cabina", "Diseño ergonómico"],
  },
  {
    id: 6,
    name: "Sensor de Temperatura",
    slug: "sensor-temperatura",
    category: "Sensores",
    description: "Monitorea la temperatura en tiempo real del vehículo o carga.",
    price: "A cotizar",
    image: "/img/equipos/sensor-temperatura.png",
    features: ["Alta precisión", "Monitoreo 24/7", "Reportes en línea"],
  },
  {
    id: 7,
    name: "Sensor de Distracción",
    slug: "sensor-distraccion",
    category: "Sensores",
    description: "Detecta distracciones o fatiga del conductor.",
    price: "A cotizar",
    image: "/img/equipos/sensor-distraccion.png",
    features: ["IA integrada", "Prevención de accidentes", "Alertas inmediatas"],
  },
  {
    id: 8,
    name: "Identificador de Chofer",
    slug: "identificador-chofer",
    category: "Control de Acceso",
    description: "Permite identificar al operador antes de encender el vehículo.",
    price: "A cotizar",
    image: "/img/equipos/identificador-chofer.png",
    features: ["RFID/llave", "Control total", "Seguridad avanzada"],
  },
  {
    id: 9,
    name: "Sensor de Combustible",
    slug: "sensor-combustible",
    category: "Monitoreo",
    description: "Mide y reporta el consumo y nivel de combustible.",
    price: "A cotizar",
    image: "/img/equipos/sensor-combustible.png",
    features: ["Prevención de robos", "Alta precisión", "Alertas de consumo"],
  },
  {
    id: 10,
    name: "Detector de Activación",
    slug: "detector-activacion",
    category: "Sensores",
    description: "Monitorea encendido o uso de sistemas en el vehículo.",
    price: "A cotizar",
    image: "/img/equipos/detector-activacion.png",
    features: ["Notificación instantánea", "Integración total", "Fácil instalación"],
  },
  {
    id: 11,
    name: "Sensor Quinta Rueda",
    slug: "sensor-quinta-rueda",
    category: "Sensores",
    description: "Detecta desconexión o manipulación de la quinta rueda.",
    price: "A cotizar",
    image: "/img/equipos/sensor-quinta-rueda.png",
    features: ["Prevención de robos", "Alertas en tiempo real", "Robusto"],
  },
  {
    id: 12,
    name: "Tapón Trampa",
    slug: "tapon-trampa",
    category: "Seguridad",
    description: "Accesorio de seguridad para evitar robos de combustible.",
    price: "A cotizar",
    image: "/img/equipos/tapon-trampa.png",
    features: ["Antirrobo", "Alta resistencia", "Compatible universal"],
  },
  {
    id: 13,
    name: "Chapas Neumáticas",
    slug: "chapas-neumaticas",
    category: "Seguridad",
    description: "Bloqueo neumático para puertas de seguridad vehicular.",
    price: "A cotizar",
    image: "/img/equipos/chapas-neumaticas.png",
    features: ["Bloqueo seguro", "Resistente", "Control remoto"],
  },
  {
    id: 14,
    name: "Sensor de Descarga de Concreto",
    slug: "sensor-concreto",
    category: "Sensores Especiales",
    description: "Monitorea la apertura y descarga en camiones de concreto.",
    price: "A cotizar",
    image: "/img/equipos/sensor-concreto.png",
    features: ["Alta precisión", "Monitoreo remoto", "Prevención de fugas"],
  },
  {
    id: 15,
    name: "Conectividad a la Computadora del Vehículo",
    slug: "conectividad-computadora",
    category: "Monitoreo",
    description: "Integración con la computadora vehicular para diagnóstico.",
    price: "A cotizar",
    image: "/img/equipos/conectividad.png",
    features: ["Datos en tiempo real", "Lectura OBD-II", "Alertas automáticas"],
  },
  {
    id: 16,
    name: "Conteo de Pasaje",
    slug: "conteo-pasaje",
    category: "Monitoreo de Flota",
    description: "Sistema automático de conteo de pasajeros.",
    price: "A cotizar",
    image: "/img/equipos/conteo-pasaje.png",
    features: ["Precisión alta", "Estadísticas en línea", "Fácil instalación"],
  },
  {
    id: 17,
    name: "Acelerómetro",
    slug: "acelerometro",
    category: "Sensores",
    description: "Mide aceleraciones y movimientos bruscos en conducción.",
    price: "A cotizar",
    image: "/img/equipos/acelerometro.png",
    features: ["Detección de impactos", "Datos telemáticos", "Prevención"],
  },
  {
    id: 18,
    name: "Sensor de Identificación",
    slug: "sensor-identificacion",
    category: "Control de Acceso",
    description: "Permite identificar al conductor o vehículo mediante sensores.",
    price: "A cotizar",
    image: "/img/equipos/sensor-identificacion.png",
    features: ["Alta seguridad", "Integración RFID", "Automatización"],
  },
  {
    id: 19,
    name: "Amplificador de Señal Celular",
    slug: "amplificador-senal",
    category: "Comunicación",
    description: "Mejora la señal celular en zonas de baja cobertura.",
    price: "A cotizar",
    image: "/img/equipos/amplificador-senal.png",
    features: ["Señal estable", "Cobertura amplia", "Instalación sencilla"],
  },
  {
    id: 20,
    name: "Alarmas",
    slug: "alarmas",
    category: "Seguridad",
    description: "Sistemas de alarma avanzados para protección vehicular.",
    price: "A cotizar",
    image: "/img/equipos/alarmas.png",
    features: ["Sonoras y visuales", "Alertas inmediatas", "Disuasión efectiva"],
  },
  {
    id: 21,
    name: "Gps portátil",
    slug: "gps-portatil",
    category: "Rastreo",
    description: "Dispositivo GPS compacto y fácil de transportar para rastreo en tiempo real.",
    price: "A cotizar",    
    image: "/img/equipos/gpsportatil.png",
    features: ["Sonoras y visuales", "Alertas inmediatas", "Disuasión efectiva"],
  },
]
